### ISSUE TITLE
Disappearing hover bug in reorderable

### ISSUE THREAD

**Issue by grassick** [mWater/react-library#18]
If I drag the second item up over the bottom half of the first item, the second item disappears from the list, leaving a blank space. I expected it to stay there in faded view.

**Comment by broncha** [comment]
This was fixed in d805968e2aa0a867a56732de152425651029395a

**Comment by grassick** [comment]
I'm afraid I still get this one in the latest version of master. Can you double-check it? I can show you over screenshare if that would help.
